# This file is generated by Anlogic Timing Wizard. 22 11 2019

#Created Clock
create_clock -name vga_clk_w -period 41.6 -waveform {0 20.8} 
create_clock -name sys_clk -period 41.6 -waveform {0 20.8} 
create_clock -name clk -period 41.6 -waveform {0 20.8} 

